import classNames from 'classnames';
import { useMemo, useRef, useState, type DragEvent } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { AppDispatch, StorageState } from '../../../../store';
import { useDictionary } from '../../../../store/selectors/translations';
import { controller } from '../../../../../main.tsx';
import { SUPPORTED_EXTENSIONS_ACCEPT } from '../../../../../viewModel/domain/supportedFileExtensions.ts';

/** Больше в строку над запросом не помещается, остальные файлы не показываем */
const VISIBLE_FILES = 3;

const baseName = (path: string) => path.slice(path.lastIndexOf('/') + 1);

/**
 * Файлы в чате агентского режима. Файлового менеджера там нет, поэтому
 * загрузка и выбор файла для агента живут прямо над полем запроса: пунктирная
 * зона в пустом чате и ряд из нескольких файлов проекта с кнопкой загрузки
 */
export const AgentFiles = ({ isEmpty }: { isEmpty: boolean }) => {
    const dispatch = useDispatch<AppDispatch>();
    const dictionary = useSelector(useDictionary);
    const isAuthenticated = useSelector(
        (state: StorageState) => state.user.isAuthenticated
    );
    const isRunning = useSelector((state: StorageState) => {
        const s = state.chat.requestState;
        return s === 'running' || s === 'connecting';
    });
    const files = useSelector((state: StorageState) => state.project.files);
    const recentFiles = useSelector(
        (state: StorageState) => state.chat.recentFiles
    );
    const inputRef = useRef<HTMLInputElement>(null);
    const [dragging, setDragging] = useState(false);

    // загруженные из чата первыми: человек сразу видит свой файл в ряду
    const visibleFiles = useMemo(() => {
        const names = files
            .filter((file) => !file.autogenerated)
            .map((file) => file.fileName);
        const recent = recentFiles.filter((name) => names.includes(name));
        const rest = names.filter((name) => !recent.includes(name));
        return [...recent, ...rest].slice(0, VISIBLE_FILES);
    }, [files, recentFiles]);

    // окно выбора файла браузер открывает только прямо из клика
    const pickFiles = () => {
        if (!isAuthenticated) {
            dispatch(controller.onAgentFilesGuestRequest());
            return;
        }
        inputRef.current?.click();
    };

    const addFiles = (list: FileList | null, method: 'picker' | 'drop') => {
        const added = Array.from(list ?? []);
        if (added.length > 0) {
            dispatch(
                controller.onAgentFilesAddedRequest({ files: added, method })
            );
        }
    };

    const onDragOver = (event: DragEvent) => {
        if (!event.dataTransfer.types.includes('Files')) {
            return;
        }
        event.preventDefault();
        setDragging(true);
    };

    const onDrop = (event: DragEvent) => {
        event.preventDefault();
        setDragging(false);
        addFiles(event.dataTransfer.files, 'drop');
    };

    const text = dictionary.agent_chat.files;

    return (
        <>
            {isEmpty && (
                <div
                    role="button"
                    tabIndex={0}
                    className={classNames('agent-files__drop', {
                        'agent-files__drop--active': dragging,
                    })}
                    onClick={pickFiles}
                    onKeyDown={(event) => {
                        if (event.key === 'Enter' || event.key === ' ') {
                            event.preventDefault();
                            pickFiles();
                        }
                    }}
                    onDragOver={onDragOver}
                    onDragLeave={() => setDragging(false)}
                    onDrop={onDrop}
                >
                    <UploadIcon size={24} />
                    <span className="agent-files__drop-title">
                        {text.drop_title}
                    </span>
                    <span className="agent-files__drop-hint">
                        {text.drop_hint}
                    </span>
                    {!isAuthenticated && (
                        <span className="agent-files__drop-guest">
                            {text.guest_hint}
                        </span>
                    )}
                </div>
            )}
            <div className="agent-files__row">
                {visibleFiles.map((name) => (
                    <button
                        key={name}
                        type="button"
                        className="agent-files__file"
                        title={name}
                        disabled={isRunning}
                        onClick={() =>
                            dispatch(
                                controller.onAgentFileMentionedRequest({
                                    name,
                                })
                            )
                        }
                    >
                        <FileIcon />
                        <span className="agent-files__file-name">
                            {baseName(name)}
                        </span>
                    </button>
                ))}
                <button
                    type="button"
                    className="agent-files__upload"
                    disabled={isRunning}
                    onClick={pickFiles}
                >
                    <UploadIcon size={18} />
                    {text.upload}
                </button>
                <input
                    ref={inputRef}
                    type="file"
                    multiple
                    accept={SUPPORTED_EXTENSIONS_ACCEPT}
                    className="agent-files__input"
                    data-testid="agent-files-input"
                    onChange={(event) => {
                        addFiles(event.target.files, 'picker');
                        // тот же файл можно выбрать снова, например после удаления
                        event.target.value = '';
                    }}
                />
            </div>
        </>
    );
};

const UploadIcon = ({ size }: { size: number }) => (
    <svg
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        aria-hidden="true"
    >
        <path
            d="M12 15V4M7.5 8.5 12 4l4.5 4.5M4 15v3.5A1.5 1.5 0 0 0 5.5 20h13a1.5 1.5 0 0 0 1.5-1.5V15"
            stroke="currentColor"
            strokeWidth="1.6"
            strokeLinecap="round"
            strokeLinejoin="round"
        />
    </svg>
);

const FileIcon = () => (
    <svg
        width="16"
        height="16"
        viewBox="0 0 16 16"
        fill="none"
        aria-hidden="true"
    >
        <path
            d="M9 2H4.5A1.5 1.5 0 0 0 3 3.5v9A1.5 1.5 0 0 0 4.5 14h7a1.5 1.5 0 0 0 1.5-1.5V6M9 2l4 4M9 2v4h4"
            stroke="currentColor"
            strokeWidth="1.2"
            strokeLinejoin="round"
        />
    </svg>
);
