services:
  bff:
    container_name: bff
    hostname: bff
    image: cr.yandex/crpjhav5dledksn6gaeo/type-4:1.2.1.10
    environment:
      FRONTEND_FOLDER: /tmp/frontend/
    volumes:
      - source: ./dist
        target: /tmp/frontend
        type: bind
    ports:
      - "8888:8888"