import { FILE_NAME, FILE_URL, mockContext } from '../common.ts';

function mockFileFetch(status: number, body: string) {
    return jest.fn().mockResolvedValue({
        ok: status >= 200 && status < 300,
        status,
        text: async () => body,
    });
}

test('onTextFileOpened does not put 404 body into the editor', async () => {
    const { textFileEditorService, repository } = mockContext();
    repository.projectViewModelRepository.setFiles([
        { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
    ]);
    const toastSpy = jest.spyOn(repository, 'toast');
    global.fetch = mockFileFetch(404, '404: file not found');

    await textFileEditorService.onTextFileOpened(FILE_NAME);

    expect(repository.ideViewModelRepository.activeTextFile()).toBe(null);
    expect(repository.ideViewModelRepository.textFileContent()).toBe('');
    expect(repository.ideViewModelRepository.loadTextFileRequestState()).toBe(
        'unknown'
    );
    expect(toastSpy).toHaveBeenCalledWith(
        repository.dictionary.filemanager.errors.internalError,
        'error'
    );
});

test('reload of an open file does not switch the editor to loading', async () => {
    const { textFileEditorService, repository } = mockContext();
    repository.projectViewModelRepository.setFiles([
        { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
    ]);
    repository.ideViewModelRepository.setActiveTextFile(FILE_NAME);
    repository.ideViewModelRepository.setTextFileContent('old content');
    repository.ideViewModelRepository.setLoadTextFileRequestState('ok');
    global.fetch = mockFileFetch(200, 'new content');

    const states: string[] = [];
    const originalSetLoad =
        repository.ideViewModelRepository.setLoadTextFileRequestState;
    repository.ideViewModelRepository.setLoadTextFileRequestState = (state) => {
        states.push(state);
        originalSetLoad(state);
    };

    await textFileEditorService.reloadActiveTextFileIfOpen();

    expect(states).not.toContain('loading');
    expect(repository.ideViewModelRepository.textFileContent()).toBe(
        'new content'
    );
    expect(repository.ideViewModelRepository.loadTextFileRequestState()).toBe(
        'ok'
    );
});
