import {
    FILE_NAME,
    FILE_URL,
    mockContext,
    PROJECT_ID,
    PROJECT_TITLE,
    USER_EMAIL,
    USER_ID,
} from '../common.ts';
import { Events } from '../../../model/service/ObserverService.ts';
import { Hunk } from '../../../model/domain.ts';

function mockFileFetch(status: number, body: string) {
    return jest.fn().mockResolvedValue({
        ok: status >= 200 && status < 300,
        status,
        text: async () => body,
    });
}

test('onTextFileOpened does not put 404 body into the editor', async () => {
    const { textFileEditorService, repository, observerService } =
        mockContext();
    repository.projectViewModelRepository.setFiles([
        { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
    ]);
    const toastSpy = jest.spyOn(repository, 'toast');
    const onEvent = jest.spyOn(observerService, 'onEvent');
    global.fetch = mockFileFetch(404, '404: file not found');

    await textFileEditorService.onTextFileOpened(FILE_NAME);

    expect(repository.ideViewModelRepository.activeTextFile()).toBe(null);
    expect(repository.ideViewModelRepository.textFileContent()).toBe('');
    expect(repository.ideViewModelRepository.loadTextFileRequestState()).toBe(
        'unknown'
    );
    expect(toastSpy).toHaveBeenCalledWith(
        repository.dictionary.filemanager.errors.internalError,
        'error'
    );
    expect(onEvent).toHaveBeenCalledWith(
        Events.EVENT_RPI_UNKNOWN,
        expect.objectContaining({ source: 'rpi' })
    );
});

test('reload of an open file does not switch the editor to loading', async () => {
    const { textFileEditorService, repository } = mockContext();
    repository.projectViewModelRepository.setFiles([
        { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
    ]);
    repository.ideViewModelRepository.setActiveTextFile(FILE_NAME);
    repository.ideViewModelRepository.setTextFileContent('old content');
    repository.ideViewModelRepository.setLoadTextFileRequestState('ok');
    global.fetch = mockFileFetch(200, 'new content');

    const states: string[] = [];
    const originalSetLoad =
        repository.ideViewModelRepository.setLoadTextFileRequestState;
    repository.ideViewModelRepository.setLoadTextFileRequestState = (state) => {
        states.push(state);
        originalSetLoad(state);
    };

    await textFileEditorService.reloadActiveTextFileIfOpen();

    expect(states).not.toContain('loading');
    expect(repository.ideViewModelRepository.textFileContent()).toBe(
        'new content'
    );
    expect(repository.ideViewModelRepository.loadTextFileRequestState()).toBe(
        'ok'
    );
});

// на сервере файл уже с правками агента, hunks только описывают их
const fileHunk = (
    id: string,
    type: 'addLinesToFile' | 'deleteLinesFromFile',
    startLine: number,
    endLine: number,
    text: string
): Hunk => ({ id, type, fileName: FILE_NAME, startLine, endLine, text });

test.each([
    {
        name: 'deleted line had the same line below it',
        stored: '\\begin{itemize}\n\\item a\n\\item b\n\\end{itemize}',
        hunks: [fileHunk('d', 'deleteLinesFromFile', 3, 3, '\\item b')],
    },
    {
        name: 'deleted blank line sat in a paragraph gap',
        stored: 'para 1\n\npara 2',
        hunks: [fileHunk('d', 'deleteLinesFromFile', 2, 2, '')],
    },
    {
        // диапазон 3..3 на строку короче текста: \n в конце только завершает его
        name: 'text appended at the end ends with a line break',
        stored: 'a\nb\nNEW\n',
        hunks: [fileHunk('a', 'addLinesToFile', 3, 3, 'NEW\n')],
    },
    {
        name: 'replacement starts with the replaced lines',
        stored: 'h\nx\ny\nz\nt',
        hunks: [
            fileHunk('d', 'deleteLinesFromFile', 2, 3, 'x\ny'),
            fileHunk('a', 'addLinesToFile', 2, 4, 'x\ny\nz'),
        ],
    },
    {
        name: 'file and hunk text use CRLF',
        stored: 'a\r\nNEW 1\r\nNEW 2\r\nb\r\n',
        hunks: [fileHunk('a', 'addLinesToFile', 2, 3, 'NEW 1\r\nNEW 2')],
    },
    {
        name: 'repeated edit of one place is merged out of file order',
        stored: 'alpha\nSECOND\nFIRST\ngamma',
        hunks: [fileHunk('a', 'addLinesToFile', 2, 3, 'FIRST\nSECOND')],
    },
    {
        name: 'hunks lag behind the file during an agent run',
        stored: 'a\nUP\nb\nc\nd\nDOWN\ne',
        hunks: [fileHunk('a', 'addLinesToFile', 5, 5, 'DOWN')],
    },
])(
    'file with agent hunks is shown as stored: $name',
    async ({ stored, hunks }) => {
        const { textFileEditorService, repository } = mockContext();
        repository.projectViewModelRepository.setFiles([
            { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
        ]);
        repository.ideViewModelRepository.setHunks(hunks);
        global.fetch = mockFileFetch(200, stored);

        await textFileEditorService.onTextFileOpened(FILE_NAME);

        expect(repository.ideViewModelRepository.textFileContent()).toBe(
            stored
        );
    }
);

describe('reload while typed text is not saved yet', () => {
    // автосохранение ждёт секунду, настоящий таймер отправил бы загрузку
    beforeEach(() => {
        jest.useFakeTimers();
    });

    afterEach(() => {
        jest.useRealTimers();
    });

    function openedFile(content: string) {
        const context = mockContext();
        context.repository.projectViewModelRepository.setFiles([
            { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
        ]);
        context.repository.ideViewModelRepository.setActiveTextFile(FILE_NAME);
        context.repository.ideViewModelRepository.setTextFileContent(content);
        context.repository.ideViewModelRepository.setLoadTextFileRequestState(
            'ok'
        );
        return context;
    }

    function signInToProject(
        repository: ReturnType<typeof mockContext>['repository'],
        readonly: boolean
    ) {
        repository.userViewModelRepository.setUserInfo({
            isAuthenticated: true,
            email: USER_EMAIL,
            id: USER_ID,
            privacyPolicyAccepted: true,
            crossBorderDataTransferPolicyAccepted: true,
            tokenBalance: 0,
        });
        repository.projectViewModelRepository.setProject({
            projectId: PROJECT_ID,
            userId: USER_ID,
            title: PROJECT_TITLE,
            lastModified: '2026-09-06T14:00:00Z',
            isPublic: false,
            projectType: 'markdown',
            program: { segments: [], parameters: { roundStrategy: 'noRound' } },
        });
        repository.projectViewModelRepository.setReadOnly(readonly);
    }

    test('reload is skipped and keeps the typed text', async () => {
        const { textFileEditorService, repository } = openedFile('stored');
        global.fetch = mockFileFetch(200, 'stored');

        textFileEditorService.onTextFileContentChanged('stored!');
        await textFileEditorService.reloadActiveTextFileIfOpen();

        expect(global.fetch).not.toHaveBeenCalled();
        expect(repository.ideViewModelRepository.textFileContent()).toBe(
            'stored!'
        );
    });

    test('reload that started before typing does not overwrite the typed text', async () => {
        const { textFileEditorService, repository } = openedFile('stored');
        let answer: (body: string) => void = () => undefined;
        global.fetch = jest.fn().mockReturnValue(
            new Promise((resolve) => {
                answer = (body) =>
                    resolve({ ok: true, status: 200, text: async () => body });
            })
        );

        const reload = textFileEditorService.reloadActiveTextFileIfOpen();
        textFileEditorService.onTextFileContentChanged('stored!');
        answer('stored');
        await reload;

        expect(repository.ideViewModelRepository.textFileContent()).toBe(
            'stored!'
        );
    });

    test('reload after a failed save keeps the typed text', async () => {
        const { textFileEditorService, repository, rpi } = openedFile('stored');
        signInToProject(repository, false);
        rpi.uploadFileRequest = jest.fn().mockResolvedValue({
            code: 500,
            body: {},
            isOk: false,
            isUnauth: false,
            isForbidden: false,
        });
        global.fetch = mockFileFetch(200, 'stored');

        textFileEditorService.onTextFileContentChanged('stored!');
        // автосохранение ушло и упало, набранное есть только на экране
        await jest.advanceTimersByTimeAsync(2000);
        await textFileEditorService.reloadActiveTextFileIfOpen();

        expect(rpi.uploadFileRequest).toHaveBeenCalledTimes(1);
        expect(global.fetch).not.toHaveBeenCalled();
        expect(repository.ideViewModelRepository.textFileContent()).toBe(
            'stored!'
        );
    });

    test('typing in a read-only project does not block reload', async () => {
        const { textFileEditorService, repository } = openedFile('stored');
        signInToProject(repository, true);
        global.fetch = mockFileFetch(200, 'stored by owner');

        textFileEditorService.onTextFileContentChanged('stored!');
        // чужой проект не сохраняется, таймер автосохранения отрабатывает впустую
        await jest.advanceTimersByTimeAsync(2000);
        await textFileEditorService.reloadActiveTextFileIfOpen();

        expect(repository.ideViewModelRepository.textFileContent()).toBe(
            'stored by owner'
        );
    });

    test('guest typing does not hide the next agent run in the file', async () => {
        const { textFileEditorService, hunkService, repository } =
            mockContext();
        const createdFile = (run: string, text: string): Hunk[] => [
            { id: `${run}-file`, type: 'addFile', fileName: FILE_NAME },
            {
                id: `${run}-lines`,
                type: 'addLinesToFile',
                fileName: FILE_NAME,
                startLine: 1,
                endLine: 1,
                text,
            },
        ];
        repository.ideViewModelRepository.setHunks(createdFile('run1', 'v1'));
        await textFileEditorService.onTextFileOpened(FILE_NAME);

        textFileEditorService.onTextFileContentChanged('v1!');
        // гостю сохранять некуда, таймер автосохранения отрабатывает впустую
        await jest.advanceTimersByTimeAsync(2000);
        hunkService.setHunksFromPrompt(createdFile('run2', 'v2'));
        await jest.advanceTimersByTimeAsync(0);

        expect(repository.ideViewModelRepository.textFileContent()).toBe('v2');
    });
});
