import { FILE_NAME, FILE_URL, mockContext } from '../common.ts';
import { Events } from '../../../model/service/ObserverService.ts';
import { Hunk } from '../../../model/domain.ts';

function mockFileFetch(status: number, body: string) {
    return jest.fn().mockResolvedValue({
        ok: status >= 200 && status < 300,
        status,
        text: async () => body,
    });
}

test('onTextFileOpened does not put 404 body into the editor', async () => {
    const { textFileEditorService, repository, observerService } =
        mockContext();
    repository.projectViewModelRepository.setFiles([
        { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
    ]);
    const toastSpy = jest.spyOn(repository, 'toast');
    const onEvent = jest.spyOn(observerService, 'onEvent');
    global.fetch = mockFileFetch(404, '404: file not found');

    await textFileEditorService.onTextFileOpened(FILE_NAME);

    expect(repository.ideViewModelRepository.activeTextFile()).toBe(null);
    expect(repository.ideViewModelRepository.textFileContent()).toBe('');
    expect(repository.ideViewModelRepository.loadTextFileRequestState()).toBe(
        'unknown'
    );
    expect(toastSpy).toHaveBeenCalledWith(
        repository.dictionary.filemanager.errors.internalError,
        'error'
    );
    expect(onEvent).toHaveBeenCalledWith(
        Events.EVENT_RPI_UNKNOWN,
        expect.objectContaining({ source: 'rpi' })
    );
});

test('reload of an open file does not switch the editor to loading', async () => {
    const { textFileEditorService, repository } = mockContext();
    repository.projectViewModelRepository.setFiles([
        { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
    ]);
    repository.ideViewModelRepository.setActiveTextFile(FILE_NAME);
    repository.ideViewModelRepository.setTextFileContent('old content');
    repository.ideViewModelRepository.setLoadTextFileRequestState('ok');
    global.fetch = mockFileFetch(200, 'new content');

    const states: string[] = [];
    const originalSetLoad =
        repository.ideViewModelRepository.setLoadTextFileRequestState;
    repository.ideViewModelRepository.setLoadTextFileRequestState = (state) => {
        states.push(state);
        originalSetLoad(state);
    };

    await textFileEditorService.reloadActiveTextFileIfOpen();

    expect(states).not.toContain('loading');
    expect(repository.ideViewModelRepository.textFileContent()).toBe(
        'new content'
    );
    expect(repository.ideViewModelRepository.loadTextFileRequestState()).toBe(
        'ok'
    );
});

// на сервере файл уже с правками агента, hunks только описывают их
const fileHunk = (
    id: string,
    type: 'addLinesToFile' | 'deleteLinesFromFile',
    startLine: number,
    endLine: number,
    text: string
): Hunk => ({ id, type, fileName: FILE_NAME, startLine, endLine, text });

test.each([
    {
        name: 'deleted line had the same line below it',
        stored: '\\begin{itemize}\n\\item a\n\\item b\n\\end{itemize}',
        hunks: [fileHunk('d', 'deleteLinesFromFile', 3, 3, '\\item b')],
    },
    {
        name: 'deleted blank line sat in a paragraph gap',
        stored: 'para 1\n\npara 2',
        hunks: [fileHunk('d', 'deleteLinesFromFile', 2, 2, '')],
    },
    {
        // диапазон 3..3 на строку короче текста: \n в конце только завершает его
        name: 'text appended at the end ends with a line break',
        stored: 'a\nb\nNEW\n',
        hunks: [fileHunk('a', 'addLinesToFile', 3, 3, 'NEW\n')],
    },
    {
        name: 'replacement starts with the replaced lines',
        stored: 'h\nx\ny\nz\nt',
        hunks: [
            fileHunk('d', 'deleteLinesFromFile', 2, 3, 'x\ny'),
            fileHunk('a', 'addLinesToFile', 2, 4, 'x\ny\nz'),
        ],
    },
    {
        name: 'file and hunk text use CRLF',
        stored: 'a\r\nNEW 1\r\nNEW 2\r\nb\r\n',
        hunks: [fileHunk('a', 'addLinesToFile', 2, 3, 'NEW 1\r\nNEW 2')],
    },
    {
        name: 'repeated edit of one place is merged out of file order',
        stored: 'alpha\nSECOND\nFIRST\ngamma',
        hunks: [fileHunk('a', 'addLinesToFile', 2, 3, 'FIRST\nSECOND')],
    },
    {
        name: 'hunks lag behind the file during an agent run',
        stored: 'a\nUP\nb\nc\nd\nDOWN\ne',
        hunks: [fileHunk('a', 'addLinesToFile', 5, 5, 'DOWN')],
    },
])(
    'file with agent hunks is shown as stored: $name',
    async ({ stored, hunks }) => {
        const { textFileEditorService, repository } = mockContext();
        repository.projectViewModelRepository.setFiles([
            { autogenerated: false, fileName: FILE_NAME, url: FILE_URL },
        ]);
        repository.ideViewModelRepository.setHunks(hunks);
        global.fetch = mockFileFetch(200, stored);

        await textFileEditorService.onTextFileOpened(FILE_NAME);

        expect(repository.ideViewModelRepository.textFileContent()).toBe(
            stored
        );
    }
);
