import { useSelector } from 'react-redux';
import { Typography } from '../../../../components/typography';
import { FileItem } from './fileItem';
import { useDictionary } from '../../../../store/selectors/translations';
import { LabkeeperFile } from '../../../../../model/domain.ts';
import { useIsProjectReadonly } from '../../../../store/selectors/program.ts';

export const FileGroup = (props: {
    files: LabkeeperFile[];
    autogenerated: boolean;
}) => {
    const dictionary = useSelector(useDictionary);
    const isReadonly = useSelector(useIsProjectReadonly);

    return (
        <div className="file-group">
            <Typography
                text={
                    props.autogenerated
                        ? dictionary.filemanager.system_files
                        : dictionary.filemanager.your_files
                }
                type="label-small"
                color="#8C98B0"
            />
            {props.files.map((file) => {
                return (
                    <FileItem
                        showDropDown={!props.autogenerated && !isReadonly}
                        file={file}
                        key={file.fileName}
                    />
                );
            })}
        </div>
    );
};
