import { ChangeEvent, LegacyRef, useCallback, useMemo, useRef } from 'react';
import { PlusIcon } from '../../../icons';
import './style.scss';
import { useDispatch, useSelector } from 'react-redux';
import { AppDispatch } from '../../../store';
import { FileGroup } from './components/fileGroup';
import { FileManagerDragZone } from './components/dragZone';
import { Button } from '../../../components/button';
import { useDictionary } from '../../../store/selectors/translations';
import { LabkeeperFile } from '../../../../model/domain.ts';
import {
    useFileInFileManager,
    useIsDraggedToFileManager,
    useIsProjectReadonly,
    useShowFileManager,
} from '../../../store/selectors/program.ts';
import { StorageState } from '../../../store';
import { controller } from '../../../../controller.ts';

export const FileManager = () => {
    const dispatch = useDispatch<AppDispatch>();
    const inputRef = useRef<HTMLInputElement>();

    /*
    GLOBAL STATE
     */
    const dictionary = useSelector(useDictionary);
    const showFileManager = useSelector(useShowFileManager);
    const getFilesRequestState = useSelector(
        (s: StorageState) => s.ide.getFilesRequestState
    );
    const isDragged = useSelector(useIsDraggedToFileManager);
    const isReadonly = useSelector(useIsProjectReadonly);
    const files = useSelector(useFileInFileManager);

    /*
    При выборе файла для загрузки
     */
    const onSelectFile = useCallback(
        async (e: ChangeEvent<HTMLInputElement>) => {
            if (e.target.files?.length) {
                const fileToUpload: File = e.target.files[0];
                if (!fileToUpload) {
                    return;
                }

                dispatch(
                    controller.onUploadFileRequest({ file: fileToUpload })
                );
            }
        },
        [dispatch]
    );

    /*
    Разделяем список файлов
     */
    const [autogenerated, usergenerated] = useMemo(() => {
        const a: LabkeeperFile[] = [];
        const u: LabkeeperFile[] = [];

        files.forEach((f) => {
            if (f.autogenerated) {
                a.push(f);
            } else {
                u.push(f);
            }
        });

        return [a, u];
    }, [files]);

    /*
    При нажатии на кнопку загрузки файла, чтобы открылась встроенная модалка
     */
    const onPressButton = useCallback(() => {
        if (inputRef.current) {
            inputRef.current.click();
        }
    }, [inputRef]);

    if (!showFileManager) {
        return <></>;
    }
    return (
        <div className="manager-container">
            <div className="manager-header">
                <div>{dictionary.filemanager.title}</div>
                <div
                    onClick={() =>
                        dispatch(
                            controller.onCrossButtonInFileManagerClickedRequest()
                        )
                    }
                    className="close-icon-container"
                >
                    <PlusIcon style={{ rotate: '45deg' }} />
                </div>
            </div>
            {
                <div
                    style={{
                        display: 'flex',
                        margin: 14,
                        flexDirection: 'column',
                        alignItems: 'center',
                        overflowY: 'auto',
                        overflowX: 'hidden',
                        gap: 14,
                        height: '100%',
                    }}
                >
                    {getFilesRequestState === 'loading' ? (
                        <div className="ide-loading-wrapper" aria-hidden>
                            <span className="ide-loading-spinner" />
                        </div>
                    ) : getFilesRequestState === 'error' ? (
                        <div className="ide-loading-wrapper" aria-hidden>
                            <div className="ide-loading-icon-with-text">
                                <span className="ide-loading-warning" />
                                <div className="ide-loading-caption">
                                    {
                                        dictionary.filemanager.errors
                                            .internalError
                                    }
                                </div>
                            </div>
                        </div>
                    ) : getFilesRequestState === 'forbidden' ? (
                        <div className="ide-loading-wrapper" aria-hidden>
                            <div className="ide-loading-icon-with-text">
                                <span className="ide-loading-warning" />
                                <div className="ide-loading-caption">
                                    {
                                        dictionary.filemanager.errors
                                            .notEnoughRights
                                    }
                                </div>
                            </div>
                        </div>
                    ) : (
                        <>
                            {isDragged ? <FileManagerDragZone /> : null}
                            {!isDragged && usergenerated.length ? (
                                <FileGroup
                                    files={usergenerated}
                                    autogenerated={false}
                                />
                            ) : null}
                            {!isDragged && autogenerated.length ? (
                                <FileGroup
                                    files={autogenerated}
                                    autogenerated
                                />
                            ) : null}
                        </>
                    )}
                </div>
            }
            {!isReadonly && (
                <div className="button-container">
                    <input
                        onChange={onSelectFile}
                        ref={inputRef as LegacyRef<HTMLInputElement>}
                        style={{ display: 'none' }}
                        type="file"
                        accept=".png, .jpg, .jpeg, .svg, .txt, .csv"
                    />
                    <Button
                        title={dictionary.filemanager.add}
                        titleIcon={() => <PlusIcon />}
                        onPress={onPressButton}
                        minimize={false}
                        rounded
                        classname="button-add-file"
                        color="inherit"
                    />
                </div>
            )}
        </div>
    );
};
