import { useMemo } from 'react';
import { PlusIcon } from '../../../icons';
import './style.scss';
import { useDispatch, useSelector } from 'react-redux';
import { AppDispatch, StorageState } from '../../../store';
import { useDictionary } from '../../../store/selectors/translations';
import {
    useFileInFileManager,
    useIsDraggedToFileManager,
    useIsProjectReadonly,
    useShowFileManager,
} from '../../../store/selectors/program.ts';
import { controller } from '../../../../main.tsx';
import { LabkeeperFile } from '../../../../model/domain.ts';
import { FileTreeView } from './FileTreeView.tsx';

export const FileManager = () => {
    const dispatch = useDispatch<AppDispatch>();

    const dictionary = useSelector(useDictionary);
    const showFileManager = useSelector(useShowFileManager);
    const getFilesRequestState = useSelector(
        (s: StorageState) => s.ide.getFilesRequestState
    );
    const isDragged = useSelector(useIsDraggedToFileManager);
    const isReadonly = useSelector(useIsProjectReadonly);
    const files = useSelector(useFileInFileManager);
    const ephemeralFolders = useSelector(
        (s: StorageState) => s.settings.ephemeralFolders
    );

    const [userFiles, autogeneratedFiles] = useMemo(() => {
        const user: LabkeeperFile[] = [];
        const system: LabkeeperFile[] = [];
        files.forEach((file) => {
            if (file.autogenerated) {
                system.push(file);
            } else {
                user.push(file);
            }
        });
        return [user, system];
    }, [files]);

    if (!showFileManager) {
        return null;
    }

    return (
        <div className="manager-container">
            <div className="manager-header">
                <div className="manager-header-title">
                    {dictionary.filemanager.title}
                </div>
                <div
                    onClick={() =>
                        dispatch(
                            controller.onCrossButtonInFileManagerClickedRequest()
                        )
                    }
                    className="close-icon-container"
                >
                    <PlusIcon style={{ rotate: '45deg' }} />
                </div>
            </div>
            <div className="manager-body">
                {getFilesRequestState === 'loading' ? (
                    <div className="ide-loading-wrapper" aria-hidden>
                        <span className="ide-loading-spinner" />
                    </div>
                ) : getFilesRequestState === 'error' ? (
                    <div className="ide-loading-wrapper" aria-hidden>
                        <div className="ide-loading-icon-with-text">
                            <span className="ide-loading-warning" />
                            <div className="ide-loading-caption">
                                {dictionary.filemanager.errors.internalError}
                            </div>
                        </div>
                    </div>
                ) : getFilesRequestState === 'forbidden' ? (
                    <div className="ide-loading-wrapper" aria-hidden>
                        <div className="ide-loading-icon-with-text">
                            <span className="ide-loading-warning" />
                            <div className="ide-loading-caption">
                                {dictionary.filemanager.errors.notEnoughRights}
                            </div>
                        </div>
                    </div>
                ) : (
                    <div className="file-tree-wrapper">
                        <FileTreeView
                            files={userFiles}
                            systemFiles={autogeneratedFiles}
                            ephemeralFolders={ephemeralFolders}
                            readonly={isReadonly}
                            isDragged={isDragged}
                        />
                    </div>
                )}
            </div>
        </div>
    );
};
