import { useMemo, useState } from 'react';
import { PlusIcon } from '../../../icons';
import './style.scss';
import { useDispatch, useSelector } from 'react-redux';
import { AppDispatch, StorageState } from '../../../store';
import { useDictionary } from '../../../store/selectors/translations';
import {
    useFileInFileManager,
    useIsDraggedToFileManager,
    useIsProjectReadonly,
    useShowFileManager,
} from '../../../store/selectors/program.ts';
import { controller } from '../../../../main.tsx';
import { LabkeeperFile } from '../../../../model/domain.ts';
import { FileTreeView } from './FileTreeView.tsx';
import { useIsMobile } from '../../../hooks/useMobile';
import { setMobileView } from '../../../store/slices/settings';
import {
    selectFileHunkEntries,
    selectFilesWithHunks,
    selectPhantomFileNames,
} from '../../../store/selectors/hunks.ts';
import type { FileHunkEntry } from '../../../../viewModel/utils/hunkGrouping.ts';

const EMPTY_FILE_HUNK_ENTRIES: FileHunkEntry[] = [];
const EMPTY_PHANTOM_FILE_NAMES: string[] = [];
const EMPTY_FILES_WITH_HUNKS = new Set<string>();

export const FileManager = () => {
    const dispatch = useDispatch<AppDispatch>();
    const isMobile = useIsMobile();

    const dictionary = useSelector(useDictionary);
    const showFileManager = useSelector(useShowFileManager);
    const getFilesRequestState = useSelector(
        (s: StorageState) => s.ide.getFilesRequestState
    );
    const isDragged = useSelector(useIsDraggedToFileManager);
    const isReadonly = useSelector(useIsProjectReadonly);
    const projectId = useSelector(
        (s: StorageState) => s.project.project?.projectId
    );
    const files = useSelector(useFileInFileManager);
    const ephemeralFolders = useSelector(
        (s: StorageState) => s.settings.ephemeralFolders
    );

    const [userFiles, autogeneratedFiles] = useMemo(() => {
        const user: LabkeeperFile[] = [];
        const system: LabkeeperFile[] = [];
        files.forEach((file) => {
            if (file.autogenerated) {
                system.push(file);
            } else {
                user.push(file);
            }
        });
        return [user, system];
    }, [files]);

    const userFileNames = useMemo(
        () => userFiles.map((file) => file.fileName),
        [userFiles]
    );
    const fileHunkEntries = useSelector((state: StorageState) =>
        isReadonly ? EMPTY_FILE_HUNK_ENTRIES : selectFileHunkEntries(state)
    );
    const filesWithHunks = useSelector((state: StorageState) =>
        isReadonly ? EMPTY_FILES_WITH_HUNKS : selectFilesWithHunks(state)
    );
    const phantomFileNames = useSelector((state: StorageState) =>
        isReadonly
            ? EMPTY_PHANTOM_FILE_NAMES
            : selectPhantomFileNames(state, userFileNames)
    );

    const [filesLoadedOnce, setFilesLoadedOnce] = useState(false);
    if (getFilesRequestState === 'ok' && !filesLoadedOnce) {
        setFilesLoadedOnce(true);
    } else if (getFilesRequestState === 'unknown' && filesLoadedOnce) {
        setFilesLoadedOnce(false);
    }

    const showInitialLoader =
        getFilesRequestState === 'loading' && !filesLoadedOnce;
    const showRefreshLoader =
        getFilesRequestState === 'loading' && filesLoadedOnce;

    if (!isMobile && !showFileManager) {
        return null;
    }

    const onClose = () => {
        if (isMobile) {
            dispatch(setMobileView('editor'));
            return;
        }

        dispatch(controller.onCrossButtonInFileManagerClickedRequest());
    };

    return (
        <div className="manager-container">
            <div className="manager-header">
                <div className="manager-header-title">
                    {dictionary.filemanager.title}
                </div>
                <div onClick={onClose} className="close-icon-container">
                    <PlusIcon style={{ rotate: '45deg' }} />
                </div>
            </div>
            <div className="manager-body">
                {showInitialLoader ? (
                    <div className="ide-loading-wrapper" aria-hidden>
                        <span className="ide-loading-spinner" />
                    </div>
                ) : getFilesRequestState === 'error' ? (
                    <div className="ide-loading-wrapper" aria-hidden>
                        <div className="ide-loading-icon-with-text">
                            <span className="ide-loading-warning" />
                            <div className="ide-loading-caption">
                                {dictionary.filemanager.errors.internalError}
                            </div>
                        </div>
                    </div>
                ) : getFilesRequestState === 'forbidden' ? (
                    <div className="ide-loading-wrapper" aria-hidden>
                        <div className="ide-loading-icon-with-text">
                            <span className="ide-loading-warning" />
                            <div className="ide-loading-caption">
                                {dictionary.filemanager.errors.notEnoughRights}
                            </div>
                        </div>
                    </div>
                ) : (
                    <div
                        className={`file-tree-wrapper${showRefreshLoader ? ' is-refreshing' : ''}`}
                    >
                        {showRefreshLoader ? (
                            <div
                                className="file-tree-loading-overlay"
                                aria-hidden
                            >
                                <span className="ide-loading-spinner" />
                            </div>
                        ) : null}
                        <FileTreeView
                            key={projectId}
                            files={userFiles}
                            systemFiles={autogeneratedFiles}
                            ephemeralFolders={ephemeralFolders}
                            readonly={isReadonly}
                            isDragged={isDragged}
                            filesWithHunks={filesWithHunks}
                            fileHunkEntries={fileHunkEntries}
                            phantomFileNames={phantomFileNames}
                        />
                    </div>
                )}
            </div>
        </div>
    );
};
