import { LabkeeperFile } from '../../../../model/domain.ts';

export type SvarEntity = {
    id: string;
    type: 'file' | 'folder';
    size?: number;
    date?: Date;
};

export type FileTreeNode = {
    name: string;
    path: string;
    type: 'file' | 'folder';
    children: FileTreeNode[];
    file?: LabkeeperFile;
};

export const pathToSvarId = (fileName: string): string => {
    if (!fileName) {
        return '/';
    }
    return fileName.startsWith('/') ? fileName : `/${fileName}`;
};

export const svarIdToPath = (id: string): string => {
    if (!id || id === '/') {
        return '';
    }
    return id.startsWith('/') ? id.slice(1) : id;
};

const folderIdFromPrefix = (prefix: string): string => pathToSvarId(prefix);

const ensureFolderChain = (
    entities: Map<string, SvarEntity>,
    folderPath: string
) => {
    if (!folderPath) {
        return;
    }
    const parts = folderPath.split('/');
    let current = '';
    for (const part of parts) {
        current = current ? `${current}/${part}` : part;
        const id = folderIdFromPrefix(current);
        if (!entities.has(id)) {
            entities.set(id, { id, type: 'folder', date: new Date() });
        }
    }
};

export const buildSvarTree = (
    files: LabkeeperFile[],
    ephemeralFolders: string[] = []
): SvarEntity[] => {
    const entities = new Map<string, SvarEntity>();

    files
        .filter((file) => !file.autogenerated)
        .forEach((file) => {
            const slashIndex = file.fileName.lastIndexOf('/');
            if (slashIndex >= 0) {
                const folderPath = file.fileName.slice(0, slashIndex);
                ensureFolderChain(entities, folderPath);
            }
            entities.set(pathToSvarId(file.fileName), {
                id: pathToSvarId(file.fileName),
                type: 'file',
                date: new Date(),
            });
        });

    ephemeralFolders.forEach((folderPath) => {
        ensureFolderChain(entities, folderPath);
    });

    return Array.from(entities.values());
};

const getOrCreateFolderNode = (
    root: FileTreeNode,
    folderPath: string
): FileTreeNode => {
    if (!folderPath) {
        return root;
    }

    const parts = folderPath.split('/');
    let current = root;
    let currentPath = '';

    for (const part of parts) {
        currentPath = currentPath ? `${currentPath}/${part}` : part;
        let child = current.children.find(
            (node) => node.type === 'folder' && node.path === currentPath
        );
        if (!child) {
            child = {
                name: part,
                path: currentPath,
                type: 'folder',
                children: [],
            };
            current.children.push(child);
        }
        current = child;
    }

    return current;
};

export const buildFileTree = (
    files: LabkeeperFile[],
    ephemeralFolders: string[] = []
): FileTreeNode[] => {
    const root: FileTreeNode = {
        name: '',
        path: '',
        type: 'folder',
        children: [],
    };

    files
        .filter((file) => !file.autogenerated)
        .forEach((file) => {
            const slashIndex = file.fileName.lastIndexOf('/');
            const parent =
                slashIndex >= 0
                    ? getOrCreateFolderNode(
                          root,
                          file.fileName.slice(0, slashIndex)
                      )
                    : root;
            const name = file.fileName.slice(slashIndex + 1);
            parent.children.push({
                name,
                path: file.fileName,
                type: 'file',
                children: [],
                file,
            });
        });

    ephemeralFolders.forEach((folderPath) => {
        getOrCreateFolderNode(root, folderPath);
    });

    const sortNodes = (nodes: FileTreeNode[]) => {
        nodes.sort((a, b) => {
            if (a.type !== b.type) {
                return a.type === 'folder' ? -1 : 1;
            }
            return a.name.localeCompare(b.name, undefined, { numeric: true });
        });
        nodes.forEach((node) => {
            if (node.children.length) {
                sortNodes(node.children);
            }
        });
    };

    sortNodes(root.children);
    return root.children;
};

export const getCurrentFolderPrefix = (path: string): string => {
    return svarIdToPath(path);
};

export const joinFolderPath = (
    folderPrefix: string,
    fileName: string
): string => {
    if (!folderPrefix) {
        return fileName;
    }
    return `${folderPrefix}/${fileName}`;
};

export const isTextFilePath = (path: string): boolean => {
    const lower = path.toLowerCase();
    return lower.endsWith('.txt') || lower.endsWith('.tex');
};

export const normalizeFolderName = (name: string): string | null => {
    const trimmed = name.trim();
    if (!trimmed || trimmed.includes('/') || trimmed.includes('..')) {
        return null;
    }
    return trimmed;
};
