import { useSelector } from "react-redux";
import { Typography } from "../../../../componenets/typography";
import { IFile } from "../models/file";
import { FileItem } from "./fileItem";
import { useDictionary } from "../../../../store/selectors/translations";

export const FileGroup = (props: {files: IFile[], autogenerated: boolean, onAfterSuccessChange?: () => any}) => {
    const dictionary = useSelector(useDictionary);
    return <div style={{display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'flex-start', gap: 7, width: '100%'}}>
        <Typography text={props.autogenerated ? dictionary.filemanager.system_files :  dictionary.filemanager.your_files } type='label-small' color="#8C98B0" />
        {
            props.files.map(file => {
                return <FileItem showDropDown={!props.autogenerated} onAfterSuccessChange={props.onAfterSuccessChange} file={file} key={file.fileName} />
            })
        }
    </div>
}