import _LogoIcon from '../../assets/logo.svg?react';
import _InterfaceTour from '../../assets/interface_tour.svg?react';
import _ShareIcon from '../../assets/share.svg?react';
import _PlusIcon from '../../assets/plus.svg?react';
import _FolderIcon from '../../assets/folder.svg?react';
import _FileIcon from '../../assets/file.svg?react';
import _CloseIcon from '../../assets/close.svg?react';
import _CloseModalIcon from '../../assets/close_modal.svg?react';
import _RightArrowIcon from '../../assets/right-arrow.svg?react';
import _SavePdfIcon from '../../assets/save-pdf.svg?react';
import _ExpandIcon from '../../assets/expand.svg?react';
import _PencilIcon from '../../assets/pencil.svg?react';
import _LinkIcon from '../../assets/link.svg?react';

import _HistoryChangerIcon from '../../assets/history_changer.svg?react';
import _SearchIcon from '../../assets/search.svg?react';
import _BookIcon from '../../assets/book.svg?react';
import _CodeSettingsIcon from '../../assets/code_settings.svg?react';
import _DotssIcon from '../../assets/dots.svg?react';
import _CheckIcon from '../../assets/check.svg?react';
import _ArrowUp from '../../assets/arrow_up-2.svg?react';

import _WarningIcon from '../../assets/warning.svg?react';

import _Login1Icon from '../../assets/login1.svg?react';
import _Login2Icon from '../../assets/login2.svg?react';

export const LogoIcon = _LogoIcon;
export const FolderIcon = _FolderIcon;
export const FileIcon = _FileIcon;
export const ArrowUp = _ArrowUp;
export const InterfaceTour = _InterfaceTour;
export const PlusIcon = _PlusIcon;
export const RightArrowIcon = _RightArrowIcon;
export const SavePdfIcon = _SavePdfIcon;
export const ExpandIcon = _ExpandIcon;
export const PencilIcon = _PencilIcon;
export const HistoryChangerIcon = _HistoryChangerIcon;
export const SearchIcon = _SearchIcon;
export const BookIcon = _BookIcon;
export const CodeSettingsIcon = _CodeSettingsIcon;
export const DotssIcon = _DotssIcon;
export const CheckIcon = _CheckIcon;
export const WarningIcon = _WarningIcon;
export const CloseIcon = _CloseIcon;
export const CloseModalIcon = _CloseModalIcon;
export const Login1Icon = _Login1Icon;
export const Login2Icon = _Login2Icon;
export const ShareIcon = _ShareIcon;
export const LinkIcon = _LinkIcon;
