import {
    buildFileTree,
    buildSvarTree,
    isTextFilePath,
    joinFolderPath,
    pathToSvarId,
    svarIdToPath,
} from '../../../view/pages/project/fileManager/svarFileTreeAdapter.ts';
import { LabkeeperFile } from '../../../model/domain.ts';

describe('svarFileTreeAdapter', () => {
    test('path conversion', () => {
        expect(pathToSvarId('folder/file.txt')).toBe('/folder/file.txt');
        expect(svarIdToPath('/folder/file.txt')).toBe('folder/file.txt');
        expect(svarIdToPath('/')).toBe('');
    });

    test('buildSvarTree creates folders from file paths', () => {
        const files: LabkeeperFile[] = [
            {
                fileName: 'folder1/folder2/file.png',
                url: 'https://example.com/file.png',
                autogenerated: false,
            },
            {
                fileName: 'root.txt',
                url: 'https://example.com/root.txt',
                autogenerated: false,
            },
        ];

        const tree = buildSvarTree(files, []);
        const ids = tree.map((item) => item.id).sort();

        expect(ids).toEqual([
            '/folder1',
            '/folder1/folder2',
            '/folder1/folder2/file.png',
            '/root.txt',
        ]);
    });

    test('buildSvarTree merges ephemeral folders', () => {
        const tree = buildSvarTree([], ['empty/folder']);
        expect(tree).toEqual([
            expect.objectContaining({ id: '/empty', type: 'folder' }),
            expect.objectContaining({ id: '/empty/folder', type: 'folder' }),
        ]);
    });

    test('buildSvarTree skips autogenerated files', () => {
        const files: LabkeeperFile[] = [
            {
                fileName: 'system.csv',
                url: 'https://example.com/system.csv',
                autogenerated: true,
            },
        ];
        expect(buildSvarTree(files, [])).toEqual([]);
    });

    test('buildFileTree creates nested hierarchy with files', () => {
        const files: LabkeeperFile[] = [
            {
                fileName: 'folder1/note.txt',
                url: 'https://example.com/note.txt',
                autogenerated: false,
            },
            {
                fileName: 'readme.txt',
                url: 'https://example.com/readme.txt',
                autogenerated: false,
            },
        ];

        const tree = buildFileTree(files, ['empty']);
        expect(tree).toHaveLength(3);
        expect(tree.find((node) => node.path === 'readme.txt')?.type).toBe(
            'file'
        );
        expect(
            tree
                .find((node) => node.path === 'folder1')
                ?.children.find((node) => node.path === 'folder1/note.txt')
        ).toBeTruthy();
        expect(tree.find((node) => node.path === 'empty')?.type).toBe('folder');
    });
});
