import { test, expect } from '@playwright/test';

/*
Тест на большое количество сегментов с текстом.
 */
test('many-segments', async ({ page }) => {
    await page.goto('/');

    // Ждем загрузки страницы и проверяем URL
    await page.waitForLoadState('domcontentloaded');
    await expect(page).toHaveURL(/.*\/project/);

    // Генерируем текст
    const linesCount = 20;
    let text = '';
    for (let i = 0; i < linesCount; i++) {
        text += 'aaaaaaaaaaaa';
        if (i + 1 < linesCount) {
            text += '\n';
        }
    }

    // Добавляем 10 MD сегментов
    for (let i = 0; i < 10; i++) {
        await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    }

    // Пишем текст в первый сегмент
    const editor = page.locator('.cm-content').nth(0);
    await editor.click();
    await editor.fill(text);
    await editor.click();

    // Проверяем снапшоты
    await expect(page).toHaveScreenshot(`many-segments/snapshot.png`);

    // Проверяем, что все сегменты были добавлены
    const segments = await page.locator('.segment-editor-container').count();
    expect(segments).toBe(10);
});

/*
Тест на механику работы кнопки ESC
 */
test('ESC-test', async ({ page }) => {
    // Перехватываем запрос default project и get project
    await page.route(
        /\/api\/v2\/public\/project\/(default|1\/get)/,
        async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    projectId: 1,
                    userId: 1,
                    title: 'Default Project',
                    lastModified: new Date().toISOString(),
                    program: {
                        segments: [],
                        parameters: {
                            roundStrategy: 'noRound',
                        },
                    },
                }),
            });
        }
    );
    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: true,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    // Добавляем маркдаун
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    const editor = page.locator('.cm-content').nth(0);
    await editor.click();
    await editor.pressSequentially('aaa\n\n${a}\n', { delay: 100 });
    await editor.click();

    // Перехватываем запрос на сохранение программы
    await page.route('/api/v2/public/project/1/program', async (route) => {
        await route.fulfill({
            status: 200,
        });
    });

    // Перехватываем запрос на компиляцию
    await page.route('/api/v2/public/project/1/compile', async (route) => {
        await route.fulfill({
            status: 203,
            contentType: 'application/json',
            body: JSON.stringify({
                errors: [
                    {
                        code: 501,
                        payload: {
                            segmentId: 1,
                            line: 2,
                            variable: null,
                            operators: null,
                            quotaIndex: 0,
                            value: null,
                            limit: null,
                            position: 0,
                        },
                    },
                ],
            }),
        });
    });

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // Открываем файловый менеджер
    await page.locator('div.file-manager-button').click();

    // Открываем поиск
    await page.locator('div.action-button').last().click();

    // Ждем, пока кнопка 'Выполнить' станет доступной для нажатия
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    await expect(page).toHaveScreenshot('ESC-test/snapshot0.png');

    // Нажимаем ESC три раза
    // Проверяем, что панели закрываются в нужном порядке
    await page.keyboard.press('Escape');
    await expect(page).toHaveScreenshot('ESC-test/snapshot1.png');
    await page.keyboard.press('Escape');
    await expect(page).toHaveScreenshot('ESC-test/snapshot2.png');
    await page.keyboard.press('Escape');
    await expect(page).toHaveScreenshot('ESC-test/snapshot3.png');
});

/*
Тест на закрытие поиска и пропадание выделения символов
*/
test('Search-test', async ({ page }) => {
    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: false,
                email: null,
                id: null,
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/default');

    // Добавляем маркдаун
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    const editor = page.locator('.cm-content').nth(0);
    await editor.click();
    await editor.pressSequentially('aaa\n\n${a}\n', { delay: 100 });
    await editor.click();

    // Открываем поиск чтобы потом закрыть его через ESC
    await page.locator('div.action-button').last().click();

    // Вводим текст в строку поиска
    await page
        .getByRole('textbox', { name: /Введите текст для поиска/i })
        .click();
    await page
        .getByRole('textbox', { name: /Введите текст для поиска/i })
        .pressSequentially('aa');

    // выходим из поиска нажатием ESC
    await page.keyboard.press('Escape');

    await expect(page).toHaveScreenshot('search-test/cross.png');

    // открываем поиск, чтобы потом закрыть чего через кнопку крестик
    await page.locator('div.action-button').last().click();

    // Вводим текст в строку поиска
    await page
        .getByRole('textbox', { name: /Введите текст для поиска/i })
        .click();
    await page
        .getByRole('textbox', { name: /Введите текст для поиска/i })
        .pressSequentially('aa');

    // Нажимаем на кнопку крестик, чтобы закрыть поисковую строку
    await page.locator('div.input-delete-icon').click();

    await expect(page).toHaveScreenshot('search-test/button.png');
});

/*
Тест на отображение большого количества ошибок и на то, что выделение ошибки пропадает после редактирования
 */
test('many-errors-test', async ({ page }) => {
    const count = 100;
    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/default');

    // собираем текст
    let text = '';
    for (let i = 0; i < count; i++) {
        text += 'a\n';
    }

    // Добавляем маркдаун
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    const editor = page.locator('.cm-content').nth(0);
    await editor.click();
    await editor.pressSequentially(text, { delay: 20 });
    await editor.click();

    // собираем большую ошибку
    const errors = [];
    for (let i = 0; i < 2 * count; i++) {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-expect-error
        errors.push({
            code: 501,
            payload: {
                segmentId: 1,
                line: i,
                variable: null,
                operators: null,
                quotaIndex: 0,
                value: null,
                limit: null,
                position: 0,
            },
        });
    }

    // Перехватываем запрос на компиляцию
    await page.route('/api/v2/public/compile', async (route) => {
        await route.fulfill({
            status: 203,
            contentType: 'application/json',
            body: JSON.stringify({
                errors: errors,
            }),
        });
    });

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // проверяем, что ошибки отображаются корректно
    await expect(page).toHaveScreenshot('search-test/errors.png');

    // нажимаем ENTER в сегменте и проверяем, что выделение ошибок пропало
    await editor.click();
    await editor.press('Enter');

    // проверяем, что ошибки отображаются корректно
    await expect(page).toHaveScreenshot('search-test/no-errors.png');
});

/*
Тест на отображение элементов маркдауна
 */
test('md2pdf-test', async ({ page }) => {
    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/default');

    const text = `
https://md2pdf.netlify.com/

> Awesome Markdown to PDF!

1. Click button choose \`.md\` file.
3. Click **Transform**!
4. Switch 'Destination' to **Save as PDF**.

- After click \`Transform\` button, inverse the checkbox of **'Headers and Footers'**. 
- **反選頁首與頁尾**.
- Github: [@realdennis](https://github.com/realdennis)
- What about me: ☕ 、 👨🏻‍💻️、 🍕、 🎞️

\`\`\`javascript
// index.js
function Hello(){
  console.log('World!')
}
Hello();
\`\`\`

| 1aaa | 2ddd | 3fff | vvv  |   |   |   |   |   |   |   |   |   |      |
|------|------|------|------|---|---|---|---|---|---|---|---|---|------|
| rrr  | 5eee | e    | vvvd |   |   |   |   |   |   |   |   |   |      |
| eee  | eee  | rrr  | fff  |   |   |   |   |   |   |   |   |   |      |
| rr   | rrr  | ddd  | rrr  |   |   |   |   |   |   |   |   |   |      |
|      |      |      |      |   |   |   |   |   |   |   |   |   |      |
|      |      |      |      |   |   |   |   |   |   |   |   |   |      |
|      |      |      |      |   |   |   |   |   |   |   |   |   |      |
|      |      |      |      |   |   |   |   |   |   |   |   |   |      |
|      |      |      |      |   |   |   |   |   |   |   |   |   |      |
|      |      |      |      |   |   |   |   |   |   |   |   |   |      |
|      |      |      |      |   |   |   |   |   |   |   |   |   | gggg |
    `;

    // Добавляем маркдаун
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    const editor = page.locator('.cm-content').nth(0);
    await editor.click();
    await editor.fill(text);
    await editor.click();

    // Перехватываем запрос на компиляцию
    await page.route('/api/v2/public/compile', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                segments: [
                    {
                        id: 1,
                        type: 'md',
                        statements: null,
                        text: text,
                    },
                ],
            }),
        });
    });

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // проверяем, что элементы отображаются корректно
    //await expect(page.locator('div.result-markdown')).toHaveScreenshot(
    //    'md2pdf.png'
    //);
});

/*
Тест на изменение названия проекта через Enter
*/
test('rename-project-in-editor-via-enter', async ({ page }) => {
    // Перехватываем запрос default project и get project
    await page.route(
        /\/api\/v2\/public\/project\/(default|1\/get)/,
        async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    projectId: 1,
                    userId: 1,
                    title: 'Default Project',
                    lastModified: new Date().toISOString(),
                    program: {
                        segments: [],
                        parameters: {
                            roundStrategy: 'noRound',
                        },
                    },
                }),
            });
        }
    );
    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: true,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    let requestMade = false;

    // Перехватываем запрос на изменение названия проекта
    await page.route('/api/v2/public/project/1/title*', async (route) => {
        requestMade = true;
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isOk: true,
            }),
        });
    });

    // нажимаем кнопку изменения названия
    await page.locator('div.change-titlepress-button').click();

    // изменяем название
    await page.locator('input.change-title-input').pressSequentially('abc');

    // нажимаем enter
    await page.locator('input.change-title-input').press('Enter');

    // проверяем, что запрос был сделан
    expect(requestMade).toBeTruthy();
});

/*
Переименование проекта через нажатие в другое место
 */
test('rename-project-in-editor-via-press', async ({ page }) => {
    // Перехватываем запрос default project и get project
    await page.route(
        /\/api\/v2\/public\/project\/(default|1\/get)/,
        async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    projectId: 1,
                    userId: 1,
                    title: 'Default Project',
                    lastModified: new Date().toISOString(),
                    program: {
                        segments: [],
                        parameters: {
                            roundStrategy: 'noRound',
                        },
                    },
                }),
            });
        }
    );
    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: true,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    let requestMade = false;

    // Перехватываем запрос на изменение названия проекта
    await page.route('/api/v2/public/project/1/title*', async (route) => {
        requestMade = true;
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isOk: true,
            }),
        });
    });

    // нажимаем кнопку изменения названия
    await page.locator('div.change-titlepress-button').click();

    // изменяем название
    await page.locator('input.change-title-input').pressSequentially('abc');

    // нажимаем enter
    await page.locator('div.empty-project-placeholder-container').click();

    // проверяем, что запрос был сделан
    expect(requestMade).toBeTruthy();
});

/*
Тест на создание, перемещение и удаление большого количества сегментов
 */
test('many-segments-move', async ({ page }) => {
    const addCode = async () => {
        await page.locator('div.labkeeper_select.computation').first().click();
        await page.locator('li').first().click();
    };

    await page.goto('/');

    // Ждем загрузки страницы и проверяем URL
    await page.waitForLoadState('domcontentloaded');
    await expect(page).toHaveURL(/.*\/project/);

    // первый сегмент
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();

    // Пишем текст в первый сегмент
    const editor1 = page.locator('.cm-content').nth(0);
    await editor1.click();
    await editor1.fill('aaaa');
    await editor1.click();

    // adding second segment
    await addCode();

    // inserting text in second segment
    const editor2 = page.locator('.cm-content').nth(1);
    await editor2.click();
    await editor2.fill('bbbb');
    await editor2.click();

    // adding third segment
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();

    // inserting text in third segment
    const editor3 = page.locator('.cm-content').nth(2);
    await editor3.click();
    await editor3.fill('cccc');
    await editor3.click();

    // adding fourth segment
    await addCode();

    // inserting text in fourth segment
    const editor4 = page.locator('.cm-content').nth(3);
    await editor4.click();
    await editor4.fill('dddd');
    await editor4.click();

    // проверяем, что элементы отображаются корректно
    await expect(page).toHaveScreenshot('many-segs1.png');

    // more
    await addCode();
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    await addCode();
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    await addCode();
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();

    // проверяем, что элементы отображаются корректно
    await expect(page).toHaveScreenshot('many-segs2.png');

    // moving segment
    await page.locator('div.change-position-button').nth(1).click();
    expect(await page.locator('.cm-content').nth(0).textContent()).toBe('bbbb');
    expect(await page.locator('.cm-content').nth(1).textContent()).toBe('aaaa');
    expect(await page.locator('.cm-content').nth(2).textContent()).toBe('cccc');
    expect(await page.locator('.cm-content').nth(3).textContent()).toBe('dddd');

    // moving segment
    await page.locator('div.change-position-button').nth(4).click();
    expect(await page.locator('.cm-content').nth(0).textContent()).toBe('bbbb');
    expect(await page.locator('.cm-content').nth(1).textContent()).toBe('aaaa');
    expect(await page.locator('.cm-content').nth(2).textContent()).toBe('dddd');
    expect(await page.locator('.cm-content').nth(3).textContent()).toBe('cccc');

    // moving segment
    await page.locator('div.change-position-button').nth(3).click();
    expect(await page.locator('.cm-content').nth(0).textContent()).toBe('bbbb');
    expect(await page.locator('.cm-content').nth(1).textContent()).toBe('dddd');
    expect(await page.locator('.cm-content').nth(2).textContent()).toBe('aaaa');
    expect(await page.locator('.cm-content').nth(3).textContent()).toBe('cccc');

    // moving segment
    await page.locator('div.change-position-button').nth(5).click();
    expect(await page.locator('.cm-content').nth(0).textContent()).toBe('bbbb');
    expect(await page.locator('.cm-content').nth(1).textContent()).toBe('dddd');
    expect(await page.locator('.cm-content').nth(2).textContent()).toBe('cccc');
    expect(await page.locator('.cm-content').nth(3).textContent()).toBe('aaaa');

    // moving segment
    await page.locator('div.change-position-button').nth(0).click();
    expect(await page.locator('.cm-content').nth(0).textContent()).toBe('dddd');
    expect(await page.locator('.cm-content').nth(1).textContent()).toBe('bbbb');
    expect(await page.locator('.cm-content').nth(2).textContent()).toBe('cccc');
    expect(await page.locator('.cm-content').nth(3).textContent()).toBe('aaaa');

    // проверяем, что элементы отображаются корректно
    await expect(page).toHaveScreenshot('many-segs3.png');
});

/*
Тест удаление строк с ошибкой тремя способами:
через последовательное нажатие delete, через ctrl+a и delete, через ручное выделение и delete
 */
test('remove-lines-with-errors-test', async ({ page }) => {
    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/default');

    // Добавляем маркдаун
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    const editor = page.locator('.cm-content').nth(0);
    await editor.click();
    await editor.pressSequentially('aaaaa\n\n${a}\n', { delay: 20 });
    await editor.click();

    // Перехватываем запрос на компиляцию
    await page.route('/api/v2/public/compile', async (route) => {
        await route.fulfill({
            status: 203,
            contentType: 'application/json',
            body: JSON.stringify({
                errors: [
                    {
                        code: 501,
                        payload: {
                            segmentId: 1,
                            line: 2,
                            variable: null,
                            operators: null,
                            quotaIndex: 0,
                            value: null,
                            limit: null,
                            position: 0,
                        },
                    },
                ],
            }),
        });
    });

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // нажимаем delete
    for (let i = 0; i < 12; i++) {
        await editor.press('Backspace', { delay: 20 });
    }

    await expect(page).toHaveScreenshot('remove-error-line-via-delete.png');

    // заново заполняем
    await editor.click();
    await editor.fill('aaaaa\n\n${a}\n');

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // Выделяем весь текст через ctrl+A
    await editor.click();
    await editor.press('Control+a');
    await editor.press('Backspace');

    await expect(page).toHaveScreenshot('remove-error-line-via-ctrla.png');

    // заново заполняем
    await editor.click();
    await editor.fill('aaaaa\n\n${a}\n');

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // Выделяем часть текста через нажатие и удерживание Shift
    await editor.click();
    await page.keyboard.down('Shift');
    await editor.press('ArrowLeft');
    await editor.press('ArrowLeft');
    await editor.press('ArrowLeft');
    await editor.press('ArrowLeft');
    await editor.press('ArrowLeft');
    await page.keyboard.up('Shift');
    await editor.press('Backspace');

    await expect(page).toHaveScreenshot('remove-error-line-via-select.png');
});

/*
401 при получении дефолтного проекта
 */
test('default-project-401-test', async ({ page }) => {
    let auth = true;
    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: auth,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    // Перехватываем запрос default project и get project
    await page.route('/api/v2/public/project/default', async (route) => {
        auth = false;
        await route.fulfill({
            status: 401,
            contentType: 'application/json',
        });
    });
    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/default');

    // ждем появления toast с ошибкой
    await expect(page.locator('div.Toastify__toast').first()).toBeVisible();
});

/*
401 при получении проекта
 */
test('project-401-test', async ({ page }) => {
    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: true,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    // Перехватываем запрос default project и get project
    await page.route('/api/v2/public/project/default', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 1,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });
    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 401,
            contentType: 'application/json',
        });
    });

    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    await page.goto('/project/1');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');

    // ждем появления toast с ошибкой
    await expect(page.locator('div.Toastify__toast').first()).toBeVisible();
});

/*
401 при компиляции проекта
 */
test('compilation-401-test', async ({ page }) => {
    let auth = true;
    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: auth,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    // Перехватываем запрос default project и get project
    await page.route('/api/v2/public/project/default', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 1,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });
    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 1,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });

    // Перехватываем запрос на сохранение программы
    await page.route('/api/v2/public/project/1/program', async (route) => {
        await route.fulfill({
            status: 200,
        });
    });

    // Перехватываем запрос на компиляцию
    await page.route('/api/v2/public/project/1/compile', async (route) => {
        auth = false;
        await route.fulfill({
            status: 401,
            contentType: 'application/json',
        });
    });

    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    // Добавляем маркдаун
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    const editor = page.locator('.cm-content').nth(0);
    await editor.click();
    await editor.pressSequentially('aaa\n\n${a}\n', { delay: 100 });
    await editor.click();

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем появления toast с ошибкой
    await expect(page.locator('div.Toastify__toast')).toBeVisible();
});

/*
401 при открытии файлового менеджера
 */
test('file-manager-401-test', async ({ page }) => {
    let auth = true;
    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: auth,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    // Перехватываем запрос default project и get project
    await page.route('/api/v2/public/project/default', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 1,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });
    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 1,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });

    // Перехватываем запрос на сохранение программы
    await page.route('/api/v2/public/project/1/program', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 1,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });

    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        auth = false;
        await route.fulfill({
            status: 401,
            contentType: 'application/json',
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    // Открываем файловый менеджер
    await page.locator('div.file-manager-button').click();

    // ждем появления toast с ошибкой
    await expect(page.locator('div.Toastify__toast')).toBeVisible();
});

/*
500 при компиляции проекта
 */
test('compilation-500-test', async ({ page }) => {
    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: true,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    // Перехватываем запрос default project и get project
    await page.route('/api/v2/public/project/default', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 1,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });
    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 1,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });

    // Перехватываем запрос на сохранение программы
    await page.route('/api/v2/public/project/1/program', async (route) => {
        await route.fulfill({
            status: 200,
        });
    });

    // Перехватываем запрос на компиляцию
    await page.route('/api/v2/public/project/1/compile', async (route) => {
        await route.fulfill({
            status: 500,
            contentType: 'application/json',
        });
    });

    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('domcontentloaded');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    // Добавляем маркдаун
    await page.getByRole('button', { name: /Добавить маркдаун/i }).click();
    const editor = page.locator('.cm-content').nth(0);
    await editor.click();
    await editor.pressSequentially('aaa\n\n${a}\n', { delay: 100 });
    await editor.click();

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем появления toast с ошибкой
    await expect(page.locator('div.Toastify__toast')).toBeVisible();
});
