import { test, expect } from '@playwright/test';

/*
Тест на переименование через кнопку enter
 */
test('rename-project-via-enter', async ({ page }) => {
    // Перехватываем запрос default project и get project
    await page.route(
        /\/api\/v2\/public\/project\/(default|1\/get)/,
        async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    projectId: 1,
                    userId: 1,
                    title: 'Default Project',
                    lastModified: new Date().toISOString(),
                    program: {
                        segments: [],
                        parameters: {
                            roundStrategy: 'noRound',
                        },
                    },
                }),
            });
        }
    );
    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: true,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    // Перехватываем запрос на получение списка проектов
    await page.route('/api/v2/public/project/all', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projects: [
                    {
                        projectId: 1,
                        userId: 1,
                        title: 'Тестовый проект',
                        lastModified: '2024-03-20T12:00:00',
                    },
                ],
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('networkidle');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    await page.locator('button.image-button').click();

    await page.locator('div.change-icon-container').first().click();

    await page.locator('input.input-base').first().pressSequentially('abc');

    let requestMade = false;
    // Перехватываем запрос на изменение названия проекта
    await page.route('/api/v2/public/project/1/title*', async (route) => {
        requestMade = true;
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isOk: true,
            }),
        });
    });

    await page.locator('input.input-base').first().press('Enter');

    // проверяем, что запрос был сделан
    expect(requestMade).toBeTruthy();
});

/*
Тест на переименование через кнопку нажатие в другое место
 */
test('rename-project-via-press', async ({ page }) => {
    // Перехватываем запрос default project и get project
    await page.route(
        /\/api\/v2\/public\/project\/(default|1\/get)/,
        async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    projectId: 1,
                    userId: 1,
                    title: 'Default Project',
                    lastModified: new Date().toISOString(),
                    program: {
                        segments: [],
                        parameters: {
                            roundStrategy: 'noRound',
                        },
                    },
                }),
            });
        }
    );
    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: true,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    // Перехватываем запрос на получение списка проектов
    await page.route('/api/v2/public/project/all', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projects: [
                    {
                        projectId: 1,
                        userId: 1,
                        title: 'Тестовый проект',
                        lastModified: '2024-03-20T12:00:00',
                    },
                ],
            }),
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('networkidle');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    await page.locator('button.image-button').click();

    await page.locator('div.change-icon-container').first().click();

    await page.locator('input.input-base').first().pressSequentially('abc');

    let requestMade = false;
    // Перехватываем запрос на изменение названия проекта
    await page.route('/api/v2/public/project/1/title*', async (route) => {
        requestMade = true;
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isOk: true,
            }),
        });
    });

    await page.locator('div.project-content-container').click();

    // проверяем, что запрос был сделан
    expect(requestMade).toBeTruthy();
});

/*
Тест на 401 при получении списка файлов
 */
test('list-projects-401', async ({ page }) => {
    let auth = true;
    // Перехватываем запрос default project и get project
    await page.route(
        /\/api\/v2\/public\/project\/(default|1\/get)/,
        async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    projectId: 1,
                    userId: 1,
                    title: 'Default Project',
                    lastModified: new Date().toISOString(),
                    program: {
                        segments: [],
                        parameters: {
                            roundStrategy: 'noRound',
                        },
                    },
                }),
            });
        }
    );
    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    // Перехватываем запрос user-info
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: auth,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    // Перехватываем запрос на получение списка проектов
    await page.route('/api/v2/public/project/all', async (route) => {
        auth = false;
        await route.fulfill({
            status: 401,
            contentType: 'application/json',
        });
    });

    await page.goto('/');

    // Ждем загрузки страницы
    await page.waitForLoadState('networkidle');
    // Ждем редиректа на конкретный проект
    await expect(page).toHaveURL('/project/1');

    await page.locator('button.image-button').click();

    // ждем появления toast с ошибкой
    await expect(page.locator('div.Toastify__toast').first()).toBeVisible();
});
