import { expect, test, type Page } from '@playwright/test';
import { RouteSetup } from './mock.routeSetUp.tsx';
import { AgentHistoryEntry } from '../../model/domain.ts';

/**
 * Файлы в чате агентского режима: файлового менеджера там нет, поэтому файл
 * загружают и отдают агенту прямо над полем запроса
 */

const uuid = '2cd18704-6c3f-48cb-96f1-9a923930f8cb';

const HISTORY: AgentHistoryEntry[] = [
    {
        id: '1',
        request: 'сократи первый сегмент',
        response: 'готово',
        createdAt: '2026-09-20T10:00:00Z',
    },
];

type ProjectFile = { fileName: string; autogenerated?: boolean };

test.use({ viewport: { width: 1360, height: 900 } });

/** Список файлов живой: загрузка дописывает файл, и следующий запрос списка его вернёт */
async function openAgentMode(
    page: Page,
    {
        files = [],
        history = [],
        path = `/project/${uuid}/agent`,
    }: {
        files?: ProjectFile[];
        history?: AgentHistoryEntry[];
        path?: string;
    } = {}
) {
    const routeSetup = new RouteSetup(page);
    await routeSetup.setupGetUserInfoRequest(true);
    await routeSetup.acceptCrossBorderConsentLocally();
    await routeSetup.setupGetProjectRequest(200, 'default');
    await routeSetup.setupGetAllProjectsRequest();
    await routeSetup.setupSaveProgramRequest();
    await routeSetup.setupAgentHistoryRequest(history);
    await routeSetup.setupAgentSocket([]);
    const current = [...files];
    const uploads: string[] = [];
    await page.route(
        `**/api/v4/public/project/${uuid}/file/list**`,
        async (route) => {
            await route.fulfill({
                status: 200,
                contentType: 'application/json',
                body: JSON.stringify({
                    files: current.map((file) => ({
                        autogenerated: file.autogenerated ?? false,
                        fileName: file.fileName,
                        url: `/files/${file.fileName}`,
                    })),
                }),
            });
        }
    );
    await page.route(
        (url) => url.pathname === `/api/v4/public/project/${uuid}/file/upload`,
        async (route) => {
            const name =
                new URL(route.request().url()).searchParams.get('name') ?? '';
            uploads.push(name);
            current.push({ fileName: name });
            await route.fulfill({ status: 201, body: '"/files/x"' });
        }
    );
    await page.goto(path);
    await page.waitForLoadState('domcontentloaded');
    return { uploads: () => [...uploads] };
}

const dropZone = (page: Page) => page.locator('.agent-files__drop');
const fileChips = (page: Page) => page.locator('.agent-files__file');
const uploadButton = (page: Page) =>
    page.getByRole('button', { name: 'Upload file' });
const fileInput = (page: Page) => page.getByTestId('agent-files-input');
const promptField = (page: Page) => page.getByPlaceholder('Enter your promt');
const authModal = (page: Page) => page.locator('.auth-modal');

const fileOf = (name: string, mimeType: string) => ({
    name,
    mimeType,
    buffer: Buffer.from('content'),
});

/** Текст поля без подсказки пустого поля: она живёт виджетом внутри строки */
const promptText = (page: Page) =>
    promptField(page).evaluate((node) => {
        const copy = node.cloneNode(true) as HTMLElement;
        copy.querySelectorAll('.cm-placeholder').forEach((hint) =>
            hint.remove()
        );
        return Array.from(copy.querySelectorAll('.cm-line'))
            .map((line) => line.textContent)
            .join('\n');
    });

const mention = (name: string) =>
    `Add the file ${name} that I uploaded to the document`;

test('в пустом чате пунктирная зона загрузки над полем запроса', async ({
    page,
}) => {
    await openAgentMode(page);

    await expect(dropZone(page)).toBeVisible();
    await expect(dropZone(page)).toContainText('Drag a file here');
    await expect(dropZone(page)).toContainText(
        'or click to add it to the document'
    );
    // подпись для гостя у вошедшего не нужна
    await expect(dropZone(page)).not.toContainText('after logging in');
    const zone = await dropZone(page).boundingBox();
    const field = await page.locator('.agent-chat__field').boundingBox();
    expect(zone && field).toBeTruthy();
    // зона стоит над полем во всю его ширину и той же высоты
    expect(zone!.y + zone!.height).toBeLessThan(field!.y);
    expect(Math.abs(zone!.width - field!.width)).toBeLessThanOrEqual(1);
    expect(Math.abs(zone!.height - field!.height)).toBeLessThanOrEqual(8);
});

test('когда в чате есть история, зоны нет, а ряд файлов и кнопка остаются', async ({
    page,
}) => {
    await openAgentMode(page, {
        history: HISTORY,
        files: [{ fileName: 'data.csv' }],
    });

    await expect(page.getByText('сократи первый сегмент')).toBeVisible();
    await expect(dropZone(page)).toHaveCount(0);
    await expect(fileChips(page)).toHaveText(['data.csv']);
    await expect(uploadButton(page)).toBeVisible();
});

test('в ряду не больше трёх файлов проекта, служебные не показываются', async ({
    page,
}) => {
    await openAgentMode(page, {
        files: [
            { fileName: 'result.pdf', autogenerated: true },
            { fileName: '1-3.png' },
            { fileName: 'data.csv' },
            { fileName: 'pictures/latex_seg.png' },
            { fileName: 'notes.txt' },
        ],
    });

    await expect(fileChips(page)).toHaveText([
        '1-3.png',
        'data.csv',
        'latex_seg.png',
    ]);
    // полный путь виден в подсказке, в ряду только имя
    await expect(fileChips(page).nth(2)).toHaveAttribute(
        'title',
        'pictures/latex_seg.png'
    );
});

test('клик по файлу дописывает просьбу в запрос и не затирает набранное', async ({
    page,
}) => {
    await openAgentMode(page, {
        files: [{ fileName: 'data.csv' }, { fileName: 'pictures/plot.png' }],
    });

    await promptField(page).click();
    await page.keyboard.type('Построй график');
    await fileChips(page).nth(1).click();

    await expect
        .poll(() => promptText(page))
        .toBe(`Построй график\n${mention('pictures/plot.png')}`);
});

test('загрузка картинки через кнопку отправляет файл и просит агента вставить его', async ({
    page,
}) => {
    const { uploads } = await openAgentMode(page, {
        files: [
            { fileName: 'a.txt' },
            { fileName: 'b.txt' },
            { fileName: 'c.txt' },
        ],
    });
    await promptField(page).click();
    await page.keyboard.type('Сделай отчёт');

    const chooser = page.waitForEvent('filechooser');
    await uploadButton(page).click();
    await (await chooser).setFiles([fileOf('photo.png', 'image/png')]);

    await expect.poll(uploads).toEqual(['photo.png']);
    await expect
        .poll(() => promptText(page))
        .toBe(`Сделай отчёт\n${mention('photo.png')}`);
    // свежий файл встаёт в ряд первым, хотя в списке он последний
    await expect(fileChips(page)).toHaveText(['photo.png', 'a.txt', 'b.txt']);
});

for (const [name, mimeType] of [
    ['report.pdf', 'application/pdf'],
    ['data.csv', 'text/csv'],
    ['photo.jpg', 'image/jpeg'],
] as const) {
    test(`после загрузки ${name} агента просят вставить файл`, async ({
        page,
    }) => {
        const { uploads } = await openAgentMode(page);

        await fileInput(page).setInputFiles([fileOf(name, mimeType)]);

        await expect.poll(uploads).toEqual([name]);
        await expect.poll(() => promptText(page)).toBe(mention(name));
    });
}

test('текстовый файл загружается, но в запрос не дописывается', async ({
    page,
}) => {
    const { uploads } = await openAgentMode(page);

    await fileInput(page).setInputFiles([fileOf('notes.txt', 'text/plain')]);

    await expect.poll(uploads).toEqual(['notes.txt']);
    await expect(fileChips(page)).toHaveText(['notes.txt']);
    expect(await promptText(page)).toBe('');
});

test('файл можно перетащить в зону', async ({ page }) => {
    const { uploads } = await openAgentMode(page);

    const transfer = await page.evaluateHandle(() => {
        const data = new DataTransfer();
        data.items.add(new File(['x,y'], 'dropped.csv', { type: 'text/csv' }));
        return data;
    });
    await dropZone(page).dispatchEvent('dragover', { dataTransfer: transfer });
    await expect(dropZone(page)).toHaveClass(/agent-files__drop--active/);
    await dropZone(page).dispatchEvent('drop', { dataTransfer: transfer });

    await expect.poll(uploads).toEqual(['dropped.csv']);
    await expect.poll(() => promptText(page)).toBe(mention('dropped.csv'));
});

test('клик по зоне открывает выбор файла', async ({ page }) => {
    await openAgentMode(page);

    const chooser = page.waitForEvent('filechooser', { timeout: 5000 });
    await dropZone(page).click();
    expect((await chooser).isMultiple()).toBe(true);
});

test.describe('гость', () => {
    async function openAsGuest(page: Page) {
        const routeSetup = new RouteSetup(page);
        await routeSetup.setupGetUserInfoRequest(false);
        await routeSetup.acceptCrossBorderConsentLocally();
        await routeSetup.setupAgentSocket([]);
        let uploads = 0;
        await page.route('**/file/upload**', async (route) => {
            uploads += 1;
            await route.fulfill({ status: 201 });
        });
        await page.goto('/project/default/agent');
        await expect(dropZone(page)).toBeVisible();
        return { uploads: () => uploads };
    }

    test('в зоне видна подпись про вход', async ({ page }) => {
        await openAsGuest(page);

        await expect(
            dropZone(page).getByText('Files are available after logging in')
        ).toBeVisible();
    });

    for (const [target, locate] of [
        ['зона', dropZone],
        ['кнопка', uploadButton],
    ] as const) {
        test(`${target} открывает окно входа вместо выбора файла`, async ({
            page,
        }) => {
            await openAsGuest(page);
            let chooserOpened = false;
            page.on('filechooser', () => {
                chooserOpened = true;
            });

            await locate(page).click();

            await expect(authModal(page)).toBeVisible();
            expect(chooserOpened).toBe(false);
        });
    }

    test('брошенный в зону файл не уходит на сервер, а открывает вход', async ({
        page,
    }) => {
        const { uploads } = await openAsGuest(page);

        const transfer = await page.evaluateHandle(() => {
            const data = new DataTransfer();
            data.items.add(new File(['x'], 'a.png', { type: 'image/png' }));
            return data;
        });
        await dropZone(page).dispatchEvent('drop', { dataTransfer: transfer });

        await expect(authModal(page)).toBeVisible();
        expect(uploads()).toBe(0);
    });
});

test('во вкладке агента обычного редактора файлов в чате нет: там есть файловый менеджер', async ({
    page,
}) => {
    await openAgentMode(page, {
        path: `/project/${uuid}`,
        files: [{ fileName: 'data.csv' }],
    });
    await page.getByRole('tab', { name: 'AI agent' }).click();

    await expect(page.locator('.agent-chat')).toBeVisible();
    await expect(dropZone(page)).toHaveCount(0);
    await expect(page.locator('.agent-files__row')).toHaveCount(0);
});

test.describe('по-русски', () => {
    test.use({ locale: 'ru-RU' });

    test('колонка документа называется «Итоговый документ», а просьба русская', async ({
        page,
    }) => {
        await openAgentMode(page, { files: [{ fileName: 'data.csv' }] });

        await expect(page.locator('.viewer-header__title')).toHaveText(
            'Итоговый документ'
        );
        await expect(dropZone(page)).toContainText('Перетащите файл сюда');
        await page.getByRole('button', { name: 'data.csv' }).click();
        await expect
            .poll(() =>
                page
                    .getByPlaceholder('Опишите, что сделать с документом')
                    .textContent()
            )
            .toContain('Добавь в документ файл data.csv, который я загрузил');
    });
});
