import { expect, test, type Page } from '@playwright/test';
import { readFileSync } from 'fs';
import { RouteSetup } from './mock.routeSetUp.tsx';
import { Program } from '../../model/domain.ts';

/** Сборку агент запускает сам посреди прогона: результат доходит до редактора и просмотрщика, лента остаётся на экране до конца прогона, а после него открывается PDF */

const uuid = '2cd18704-6c3f-48cb-96f1-9a923930f8cb';

test.use({ viewport: { width: 1360, height: 900 } });

type Frame = Record<string, unknown>;

// настоящий PDF pdfTeX, его строки видны в текстовом слое просмотрщика
const PDF = readFileSync(
    new URL('./fixtures/pdf-links-selection.pdf', import.meta.url)
);
const PDF_LINE = 'Short line for selection';

const RESULT_PDF =
    'https://files.labkeeper.io/generated/user-1/project-1/result7.pdf';
const UNFINISHED_PDF =
    'https://files.labkeeper.io/generated/user-1/project-1/result8.pdf';

const LATEX_PROGRAM: Program = {
    segments: [
        {
            id: 1,
            type: 'latex',
            text: 'Alpha line one.\n\\badcommand',
            parameters: { visible: true },
        },
    ],
    parameters: { roundStrategy: 'noRound' },
};

const CALC_PROGRAM: Program = {
    segments: [
        {
            id: 1,
            type: 'computational',
            text: 'a = 10',
            parameters: { visible: true },
        },
    ],
    parameters: { roundStrategy: 'noRound' },
};

// кадры в том виде, в каком их шлёт препрод: второе поле результата приходит явным null
const started: Frame = { type: 'compilationStarted' };
const pdfCompiled = (pdfUri: string): Frame => ({
    type: 'compilationFinished',
    pdf: { pdfUri },
    markdown: null,
});
const TABLE_COMPILED: Frame = {
    type: 'compilationFinished',
    pdf: null,
    markdown: {
        segments: [
            {
                id: 1,
                type: 'computational',
                statements: [
                    {
                        type: 'table',
                        items: [['a', '10']],
                        legendVisible: false,
                    },
                ],
            },
        ],
    },
};
/** Ошибка LaTeX во второй строке сегмента: сервер считает строки с нуля */
const LATEX_FAILED: Frame = {
    type: 'compilationFailed',
    errors: {
        errors: [
            {
                code: 700,
                payload: {
                    line: 1,
                    segmentId: 1,
                    latexErrorMessage: 'Undefined control sequence.',
                    position: 0,
                    quotaIndex: 0,
                    variable: null,
                    operators: null,
                    value: null,
                    limit: null,
                    functionName: null,
                    latexFile: null,
                },
            },
        ],
        unfinishedPdfUri: UNFINISHED_PDF,
    },
};

const AGENT_DONE: Frame = {
    type: 'agentFinished',
    message: 'готово',
    stopReason: 'Done',
};

const promptField = (page: Page) => page.getByPlaceholder('Enter your promt');
const eventLabels = (page: Page) => page.locator('.agent-chat__event-label');

async function openCompilingRun(
    page: Page,
    frames: Frame[],
    options: { program: Program; latex?: boolean; neverCompiled?: boolean }
) {
    const routeSetup = new RouteSetup(page);
    await routeSetup.setupGetUserInfoRequest();
    // согласие на передачу данных проверяется отдельной спекой, здесь оно дано
    await routeSetup.acceptCrossBorderConsentLocally();
    if (options.latex) {
        routeSetup.setupLatexProject();
    }
    if (options.neverCompiled) {
        routeSetup.setupNeverCompiledProject();
    }
    await routeSetup.setupGetProjectRequest(200, 'default', options.program);
    await routeSetup.setupGetAllProjectsRequest();
    await routeSetup.setupSaveProgramRequest();
    await routeSetup.setupAgentHistoryRequest([]);
    const agent = await routeSetup.setupAgentSocketByHand();
    // до сборки файлов нет, после неё сервер кладёт собранный pdf в системные
    await page.route(`**/public/project/${uuid}/file/list**`, (route) =>
        route.fulfill({
            json: {
                files: agent.received.length
                    ? [
                          {
                              fileName: 'result7.pdf',
                              url: RESULT_PDF,
                              autogenerated: true,
                          },
                      ]
                    : [],
            },
        })
    );
    // запросы после старта прогона: сборка перечитывает файлы и баланс, как кнопка Run
    const requestsAfterStart: string[] = [];
    page.on('request', (request) => {
        if (agent.received.length) {
            requestsAfterStart.push(new URL(request.url()).pathname);
        }
    });
    const pdfRequests: string[] = [];
    await page.context().route('https://files.labkeeper.io/**', (route) => {
        pdfRequests.push(route.request().url());
        return route.fulfill({
            contentType: 'application/pdf',
            headers: { 'Access-Control-Allow-Origin': '*' },
            body: PDF,
        });
    });

    await page.goto(`/project/${uuid}`);
    await page.waitForLoadState('domcontentloaded');
    const switcher = page.locator('.mobile-view-switcher-bar__toggle');
    if (await switcher.isVisible()) {
        await switcher.click();
        await page.getByRole('option', { name: 'AI agent' }).click();
    } else {
        await page.getByRole('tab', { name: 'AI agent' }).click();
    }
    await promptField(page).fill('собери документ');
    await page.getByRole('button', { name: 'Send' }).click();
    for (const frame of frames) {
        await agent.send(frame);
    }
    return {
        send: agent.send,
        pdfRequests,
        refreshes: () =>
            requestsAfterStart.filter(
                (path) =>
                    path.endsWith('/file/list') || path.endsWith('/user-info')
            ),
    };
}

/** Лента на месте: вкладку PDF открыл бы счётчик результата, как после кнопки Run */
async function expectChatStays(page: Page) {
    await expect(page.locator('.agent-chat')).toBeVisible();
    await expect(page.getByRole('tab', { name: 'AI agent' })).toHaveAttribute(
        'aria-selected',
        'true'
    );
}

test('agent-compiled-pdf-reaches-the-viewer-while-the-chat-stays', async ({
    page,
}) => {
    const { pdfRequests, refreshes } = await openCompilingRun(
        page,
        [started, pdfCompiled(RESULT_PDF)],
        { program: LATEX_PROGRAM, latex: true }
    );

    await expect(eventLabels(page)).toHaveText([
        'Building the document',
        'Document built',
    ]);
    // просмотрщик скачивает pdf и на скрытой вкладке
    await expect.poll(() => pdfRequests).toContain(RESULT_PDF);
    await expectChatStays(page);
    // собранный pdf ложится в файлы проекта, а сборка стоит токенов
    await expect
        .poll(refreshes)
        .toEqual([
            `/api/v4/public/project/${uuid}/file/list`,
            '/api/v4/public/user-info',
        ]);

    await page.getByRole('tab', { name: 'Final document' }).click();

    await expect(
        page.locator('[data-pdf-page="0"] .textLayer').first()
    ).toContainText(PDF_LINE, { timeout: 30000 });
});

test('agent-markdown-result-reaches-the-segment-result', async ({ page }) => {
    await openCompilingRun(page, [started, TABLE_COMPILED], {
        program: CALC_PROGRAM,
    });

    await expect(eventLabels(page)).toHaveText([
        'Building the document',
        'Document built',
    ]);
    await expectChatStays(page);

    await page.getByRole('tab', { name: 'Final document' }).click();

    await expect(page.locator('#result-segment-0 td')).toHaveText(['a', '10']);
});

test('agent-compilation-errors-mark-the-segment-and-open-the-panel', async ({
    page,
}) => {
    const { pdfRequests, refreshes } = await openCompilingRun(
        page,
        [started, LATEX_FAILED],
        {
            program: LATEX_PROGRAM,
            latex: true,
        }
    );

    await expect(eventLabels(page)).toHaveText([
        'Building the document',
        'Build finished with errors',
    ]);
    await expect(
        page
            .locator('.segment-editor-container')
            .first()
            .locator('.highlight-text-editor-error')
    ).toHaveText('\\badcommand');
    await expect(
        page.locator('.problem-list-container-expanded')
    ).toContainText('Undefined control sequence.');
    // недособранный pdf уходит в просмотрщик, как после кнопки Run
    await expect.poll(() => pdfRequests).toContain(UNFINISHED_PDF);
    await expect.poll(refreshes).toHaveLength(2);
    await expectChatStays(page);
});

test.describe('agent compilation on a phone', () => {
    test.use({ viewport: { width: 390, height: 844 } });

    test('first-pdf-of-a-never-compiled-project-keeps-the-agent-screen', async ({
        page,
    }) => {
        const { pdfRequests } = await openCompilingRun(
            page,
            [started, pdfCompiled(RESULT_PDF)],
            { program: LATEX_PROGRAM, latex: true, neverCompiled: true }
        );

        await expect(eventLabels(page)).toHaveText([
            'Building the document',
            'Document built',
        ]);
        await expect.poll(() => pdfRequests).toContain(RESULT_PDF);
        // первый pdf проекта на телефоне сам открывает экран PDF, но не посреди прогона
        await expect(
            page.locator('.mobile-view-switcher-bar__label')
        ).toHaveText('AI agent');
        await expect(page.locator('.agent-chat')).toBeVisible();
    });
});

/** Лента ушла, на экране первая страница собранного PDF */
async function expectPdfShown(page: Page) {
    await expect(page.locator('.agent-chat')).toHaveCount(0);
    const firstPage = page.locator('[data-pdf-page="0"] .textLayer').first();
    await expect(firstPage).toContainText(PDF_LINE, { timeout: 30000 });
    await expect(firstPage).toBeInViewport();
}

test('finished-run-with-a-compilation-opens-the-pdf', async ({ page }) => {
    const { send } = await openCompilingRun(
        page,
        [started, pdfCompiled(RESULT_PDF)],
        { program: LATEX_PROGRAM, latex: true }
    );

    await expect(eventLabels(page)).toHaveText([
        'Building the document',
        'Document built',
    ]);
    // сборка уже прошла, а прогон ещё идёт: человек читает ленту
    await expectChatStays(page);

    await send(AGENT_DONE);

    await expect(
        page.getByRole('tab', { name: 'Final document' })
    ).toHaveAttribute('aria-selected', 'true');
    await expectPdfShown(page);
});

test.describe('agent run with a compilation on a phone', () => {
    test.use({ viewport: { width: 390, height: 844 } });

    test('finished-run-opens-the-pdf-instead-of-the-change', async ({
        page,
    }) => {
        const { send } = await openCompilingRun(page, [], {
            program: LATEX_PROGRAM,
            latex: true,
        });
        const label = page.locator('.mobile-view-switcher-bar__label');
        // правка появляется после старта: поздний маршрут перекрывает пустой список из RouteSetup
        await page.route(`**/public/project/${uuid}/hunk`, (route) =>
            route.request().method() === 'GET'
                ? route.fulfill({
                      json: {
                          hunks: [
                              {
                                  id: 'h1',
                                  type: 'addLinesToSegment',
                                  segmentId: 1,
                                  startLine: 1,
                                  endLine: 1,
                              },
                          ],
                      },
                  })
                : route.fallback()
        );

        await send({ type: 'toolCall', toolName: 'add_lines_to_segment' });
        await send(started);
        await send(pdfCompiled(RESULT_PDF));

        // агент поправил сегмент и собрал документ, прогон ещё идёт
        await expect(eventLabels(page)).toHaveText([
            'Changes have been made to segment №1',
            'Building the document',
            'Document built',
        ]);
        await expect(label).toHaveText('AI agent');
        await expect(page.locator('.agent-chat')).toBeVisible();

        await send(AGENT_DONE);

        // без сборки телефон открыл бы редактор на правке, а итог работы тут документ
        await expect(label).toHaveText('PDF');
        await expectPdfShown(page);
    });
});
