import { expect, test } from '@playwright/test';

/*
403 при получении проекта незалогиненным пользователем
 */
test('project-403-test', async ({ page }) => {
    let rejectedRequests = 0;

    // Блокируем все запросы по умолчанию
    await page.route('/api/*', async (route) => {
        rejectedRequests++;
        await route.abort();
    });

    // Разрешаем только необходимые запросы
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: false,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 403,
            contentType: 'application/json',
        });
    });

    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    await page.goto('/project/1');

    // Ждем загрузки страницы
    await page.waitForLoadState('networkidle');

    // ждем появления toast с ошибкой
    await expect(page.locator('div.Toastify__toast').first()).toBeVisible();

    // Проверяем, что не было отклоненных запросов
    expect(rejectedRequests).toBe(0);
});

/*
404 при получении проекта незалогиненным пользователем
 */
test('project-404-test', async ({ page }) => {
    let rejectedRequests = 0;

    // Блокируем все запросы по умолчанию
    await page.route('/api/*', async (route) => {
        rejectedRequests++;
        await route.abort();
    });

    // Разрешаем только необходимые запросы
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: false,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 404,
            contentType: 'application/json',
        });
    });

    await page.goto('/project/1');

    // Ждем загрузки страницы
    await page.waitForLoadState('networkidle');

    // ждем появления toast с ошибкой
    await expect(page.locator('div.Toastify__toast').first()).toBeVisible();

    // Проверяем, что не было отклоненных запросов
    expect(rejectedRequests).toBe(0);
});

/*
Успешная компиляция публичного проекта незалогиненным пользователем
 */
test('public-project-unauth-user-compilation-ok', async ({ page }) => {
    let rejectedRequests = 0;

    // Блокируем все запросы по умолчанию
    await page.route('/api/*', async (route) => {
        rejectedRequests++;
        await route.abort();
    });

    // Разрешаем только необходимые запросы
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: false,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 2,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [
                        {
                            id: 1,
                            type: 'md',
                            parameters: {
                                visible: true,
                            },
                            text: '# biba\n\n',
                        },
                    ],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });

    await page.goto('/project/1');

    // Ждем загрузки страницы
    await page.waitForLoadState('networkidle');

    // Перехватываем запрос на компиляцию
    await page.route('/api/v2/public/project/1/compile', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                segments: [
                    {
                        id: 1,
                        type: 'md',
                        statements: null,
                        text: '# biba\n\n',
                    },
                ],
            }),
        });
    });

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // проверяем, что элементы отображаются корректно
    await expect(page).toHaveScreenshot('public-compile-ok.png');

    // Проверяем, что не было отклоненных запросов
    expect(rejectedRequests).toBe(0);
});

/*
Ошибка на запрет использования файлов анонимным юзером (308)
 */
test('public-project-unauth-user-compilation-308', async ({ page }) => {
    let rejectedRequests = 0;

    // Блокируем все запросы по умолчанию
    await page.route('/api/*', async (route) => {
        rejectedRequests++;
        await route.abort();
    });

    // Разрешаем только необходимые запросы
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: false,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 2,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [
                        {
                            id: 1,
                            type: 'md',
                            parameters: {
                                visible: true,
                            },
                            text: '# biba\n\n',
                        },
                    ],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });

    await page.goto('/project/1');

    // Ждем загрузки страницы
    await page.waitForLoadState('networkidle');

    // Перехватываем запрос на компиляцию
    await page.route('/api/v2/public/project/1/compile', async (route) => {
        await route.fulfill({
            status: 203,
            contentType: 'application/json',
            body: JSON.stringify({
                errors: [
                    {
                        code: 308,
                        payload: {
                            segmentId: 1,
                            line: 1,
                            variable: null,
                            operators: null,
                            quotaIndex: 0,
                            value: null,
                            limit: null,
                            position: 0,
                        },
                    },
                ],
            }),
        });
    });

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // проверяем, что элементы отображаются корректно
    await expect(page).toHaveScreenshot('public-compile-308.png');

    // Проверяем, что не было отклоненных запросов
    expect(rejectedRequests).toBe(0);
});

/*
Успешная компиляция публичного проекта другим пользователем
 */
test('public-project-different-user-compilation-ok', async ({ page }) => {
    let rejectedRequests = 0;

    // Блокируем все запросы по умолчанию
    await page.route('/api/*', async (route) => {
        rejectedRequests++;
        await route.abort();
    });

    // Разрешаем только необходимые запросы
    await page.route('/api/v2/public/user-info', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                isAuthenticated: true,
                email: 'a@gmail.com',
                id: 1,
            }),
        });
    });

    await page.route('/api/v2/public/project/1/get', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                projectId: 1,
                userId: 2,
                title: 'Default Project',
                lastModified: new Date().toISOString(),
                program: {
                    segments: [
                        {
                            id: 1,
                            type: 'md',
                            parameters: {
                                visible: true,
                            },
                            text: '# biba\n\n',
                        },
                    ],
                    parameters: {
                        roundStrategy: 'noRound',
                    },
                },
            }),
        });
    });

    // Перехватываем запрос на список файлов
    await page.route('/api/v2/public/project/1/file/list', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                files: [
                    {
                        autogenerated: false,
                        fileName: 'example.txt',
                        url: '/files/example.txt',
                    },
                ],
            }),
        });
    });

    await page.goto('/project/1');

    // Ждем загрузки страницы
    await page.waitForLoadState('networkidle');

    // перехватываем запрос на компиляцию
    await page.route('/api/v2/public/project/1/compile', async (route) => {
        await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
                segments: [
                    {
                        id: 1,
                        type: 'md',
                        statements: null,
                        text: '# biba\n\n',
                    },
                ],
            }),
        });
    });

    // Открываем файловый менеджер
    await page.locator('div.file-manager-button').click();

    // компилируем
    await page.getByRole('button', { name: /Выполнить/i }).click();

    // ждем, когда кнопка снова станет нажимаемой
    await page
        .getByRole('button', { name: /Выполнить/i })
        .waitFor({ state: 'attached' });

    // проверяем, что элементы отображаются корректно
    await expect(page).toHaveScreenshot('different-user-public-compile-ok.png');

    // Проверяем, что не было отклоненных запросов
    expect(rejectedRequests).toBe(0);
});
